export const COLLECTIONS = {
  PRODUCTS: "products",
  ORDERS: "orders",
  USERS: "users",
  COLLECTIONS: "collections",
  BANNERS: "banners",
  HOME_SECTIONS: "homeSections",
  PROMO_BANNERS: "promobanners",
  ANNOUNCEMENTS: "announcements",
  TESTIMONIALS: "testimonials",
  FAQ: "faq",
  BLOG: "blog",
  PAGES: "pages",
  DISCOUNTS: "discounts",
  LOYALTY_CONFIG: "loyaltyConfig",
  ORDER_STATUS_CONFIG: "orderStatusConfig",
  SITE_CONFIG: "siteConfig",
  NEWSLETTER_SIGNUPS: "newsletterSignups",
} as const;
