export const ROUTES = {
  HOME: "/",
  SEARCH: "/search",
  CART: "/cart",
  CHECKOUT: "/checkout",
  BLOG: "/blog",
  ACCOUNT: "/account",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_WISHLIST: "/account/wishlist",
  ACCOUNT_ADDRESSES: "/account/addresses",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_CONTENT: "/admin/content",
  ADMIN_CONFIG: "/admin/config",
  COLLECTIONS: "/collections",
  COLLECTION: (slug: string) => `/collections/${slug}`,
  PRODUCT: (slug: string) => `/products/${slug}`,
  ORDER_TRACK: (id: string) => `/orders/${id}/track`,
  ACCOUNT_ORDER: (id: string) => `/account/orders/${id}`,
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  PAGE: (slug: string) => `/${slug}`,
  POLICY: (slug: string) => `/policies/${slug}`,
} as const;
