export const ROUTES = {
  HOME: "/",
  SEARCH: "/search",
  CART: "/cart",
  CHECKOUT: "/checkout",
  BLOG: "/blog",
  ACCOUNT: "/account",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_WISHLIST: "/account/wishlist",
  ACCOUNT_ADDRESSES: "/account/addresses",
  ACCOUNT_SUPPORT: "/account/support",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  // ─── Storefront ────────────────────────────────────────────────────────────
  FRANCHISES: "/franchise",
  FRANCHISE: (slug: string) => `/franchise/${slug}`,
  BRANDS: "/brand",
  BRAND: (slug: string) => `/brand/${slug}`,
  COLLECTIONS: "/collections",
  COLLECTION: (slug: string) => `/collections/${slug}`,
  PRODUCT: (slug: string) => `/products/${slug}`,
  ORDER_TRACK: (id: string) => `/orders/${id}/track`,
  ACCOUNT_ORDER: (id: string) => `/account/orders/${id}`,
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  PAGE: (slug: string) => `/${slug}`,
  POLICY: (slug: string) => `/policies/${slug}`,
  // ─── Admin ─────────────────────────────────────────────────────────────────
  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_FRANCHISES: "/admin/franchises",
  ADMIN_BRANDS: "/admin/brands",
  ADMIN_COLLECTIONS: "/admin/collections",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_SUPPORT: "/admin/support",
  ADMIN_NEWSLETTER: "/admin/newsletter",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_CONTENT: "/admin/content",
  ADMIN_CONFIG: "/admin/config",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_SETTINGS_PAYMENTS: "/admin/settings/payments",
  ADMIN_SETTINGS_SHIPPING: "/admin/settings/shipping",
  ADMIN_SETTINGS_NAVIGATION: "/admin/settings/navigation",
  ADMIN_SETTINGS_INTEGRATIONS: "/admin/config/integrations",
} as const;
