/**
 * seed-data.ts
 *
 * Comprehensive seed data for Hobson Collectibles.
 * All records have fixed IDs so they can be safely upserted or deleted
 * without creating duplicates.
 *
 * Collections (Firestore document ID = slug):
 *   products, collections, banners, promobanners, homeSections,
 *   announcements, testimonials, faq, discounts, siteConfig, loyaltyConfig
 */

import type { Timestamp } from "firebase-admin/firestore";

// ─── Helper ───────────────────────────────────────────────────────────────────

/** Sentinel – replaced by FieldValue.serverTimestamp() at write time */
const NOW = "__SERVER_TIMESTAMP__" as unknown as Timestamp;

// ─── Site Config ──────────────────────────────────────────────────────────────

export const SEED_SITE_CONFIG = {
  _docId: "main", // stored in siteConfig/main
  siteName: "Hobson Collectibles",
  siteTagline: "Premium Action Figures & Statues",
  logoUrl: "",
  faviconUrl: "",
  defaultOgImage: "/og-default.png",
  contactEmail: "support@hobsoncollectibles.in",
  whatsappCustomerCare: "919999999999",
  whatsappStatuses: "919999999998",
  whatsappAdminBot: "919999999997",
  phoneCustomerCare: "+91 99999 99999",
  facebookUrl: "https://facebook.com/hobsoncollectibles",
  instagramUrl: "https://instagram.com/hobsoncollectibles",
  supportHours: "Mon–Sat, 10 AM – 7 PM IST",
  freeShippingMinimum: 2999,
  inventoryLowStockDefault: 3,
  noIndexAdmin: true,
  footerCopyright: "© 2026, HOBSON COLLECTIBLES",
  locations: [
    {
      city: "Pune",
      address: "Shop 12, Koregaon Park Annexe, Pune 411001",
      phone: "+91 98765 43210",
      mapUrl: "https://maps.google.com/?q=Koregaon+Park+Pune",
      active: true,
    },
    {
      city: "Bengaluru",
      address: "Unit 4, Indiranagar 100 Ft Road, Bengaluru 560038",
      phone: "+91 98765 43211",
      mapUrl: "https://maps.google.com/?q=Indiranagar+Bangalore",
      active: true,
    },
  ],
};

// ─── Loyalty Config ───────────────────────────────────────────────────────────

export const SEED_LOYALTY_CONFIG = {
  _docId: "main", // stored in loyaltyConfig/main
  coinsPerRupee: 0.01,
  rupeePerCoin: 1,
  minCoinsToRedeem: 100,
  maxRedeemPercent: 20,
  active: true,
};

// ─── Collections ──────────────────────────────────────────────────────────────

export const SEED_COLLECTIONS = [
  // Franchise collections
  {
    slug: "marvel",
    name: "Marvel",
    type: "franchise" as const,
    bannerImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&q=80",
    description: "Iconic Marvel super-heroes from Iron Man to Spider-Man.",
    seoTitle: "Marvel Collectibles — Hobson Collectibles",
    seoDescription: "Shop premium Marvel action figures and statues.",
    active: true,
    sortOrder: 1,
  },
  {
    slug: "dc",
    name: "DC Comics",
    type: "franchise" as const,
    bannerImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&q=80",
    description: "Collectibles from the DC universe — Batman, Superman, Wonder Woman & more.",
    active: true,
    sortOrder: 2,
  },
  {
    slug: "star-wars",
    name: "Star Wars",
    type: "franchise" as const,
    bannerImage: "https://images.unsplash.com/photo-1563656157432-67560011e209?w=400&q=80",
    description: "A galaxy far, far away — brought to life in stunning detail.",
    active: true,
    sortOrder: 3,
  },
  {
    slug: "anime",
    name: "Anime",
    type: "franchise" as const,
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=400&q=80",
    description: "Dragon Ball Z, Demon Slayer, One Piece, Attack on Titan & more.",
    active: true,
    sortOrder: 4,
  },
  {
    slug: "game-of-thrones",
    name: "Game of Thrones",
    type: "franchise" as const,
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=400&q=80",
    description: "Seven Kingdoms collectibles — dragons, knights, and Iron Throne.",
    active: true,
    sortOrder: 5,
  },
  {
    slug: "warhammer",
    name: "Warhammer",
    type: "franchise" as const,
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=400&q=80",
    description: "Warhammer 40K and Age of Sigmar premium figures.",
    active: true,
    sortOrder: 6,
  },
  // Brand collections
  {
    slug: "hot-toys",
    name: "Hot Toys",
    type: "brand" as const,
    bannerImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=200&q=80",
    description: "Sixth-scale masterpieces with hyper-realistic likenesses.",
    active: true,
    sortOrder: 7,
  },
  {
    slug: "sideshow",
    name: "Sideshow Collectibles",
    type: "brand" as const,
    bannerImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&q=80",
    description: "World-class premium collectible statues and figures.",
    active: true,
    sortOrder: 8,
  },
  {
    slug: "iron-studios",
    name: "Iron Studios",
    type: "brand" as const,
    bannerImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=200&q=80",
    description: "Brazilian craftsmen behind iconic 1:10 Battle Dioramas.",
    active: true,
    sortOrder: 9,
  },
  {
    slug: "mcfarlane",
    name: "McFarlane Toys",
    type: "brand" as const,
    bannerImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&q=80",
    description: "Highly detailed collector-grade action figures at accessible prices.",
    active: true,
    sortOrder: 10,
  },
  {
    slug: "bandai",
    name: "Bandai",
    type: "brand" as const,
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=200&q=80",
    description: "S.H.Figuarts, Metal Build, and other premium Bandai lines.",
    active: true,
    sortOrder: 11,
  },
  {
    slug: "threezero",
    name: "ThreeZero",
    type: "brand" as const,
    bannerImage: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=400&q=80",
    logoImage: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=200&q=80",
    description: "Iconic 1/6 and 1/12 scale collectibles with exceptional detail.",
    active: true,
    sortOrder: 12,
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
// Fixed IDs ensure idempotent upsert/delete operations.

export const SEED_PRODUCTS = [
  // ── Hot Toys / Marvel ──────────────────────────────────────────────────────
  {
    id: "ht-iron-man-mk50",
    name: "Hot Toys Iron Man Mark L (MK50) 1/6 Scale Figure",
    slug: "hot-toys-iron-man-mark-l-mk50",
    images: [
      "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 32999,
    regularPrice: 36999,
    franchise: "marvel",
    brand: "hot-toys",
    tags: ["iron-man", "avengers", "hot-toys", "1/6-scale"],
    description:
      "<p>The iconic Iron Man Mark L armor from <em>Avengers: Infinity War</em>, faithfully recreated in 1/6 scale with die-cast leg armour, over 30 LED light features, and 25 interchangeable hands.</p><ul><li>Approx. 32 cm tall</li><li>Die-cast body parts</li><li>LED eyes &amp; chest arc reactor</li><li>30+ articulated points</li></ul>",
    specs: {
      Scale: "1/6",
      Height: "32 cm",
      Material: "ABS, Die-cast",
      Accessories: "30 interchangeable hands, nano particle effects",
      "LED Features": "Yes",
    },
    stock: 8,
    reservedStock: 0,
    availableStock: 8,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ht-spiderman-ps4",
    name: "Hot Toys Spider-Man (Advanced Suit) PS4 1/6 Scale Figure",
    slug: "hot-toys-spider-man-advanced-suit-ps4",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 28999,
    regularPrice: 31999,
    franchise: "marvel",
    brand: "hot-toys",
    tags: ["spider-man", "marvel", "hot-toys", "ps4", "1/6-scale"],
    description:
      "<p>Based on the critically acclaimed PlayStation 4 game, this sixth-scale figure features the Advanced Suit with accurate web pattern and 28 interchangeable hands.</p>",
    specs: { Scale: "1/6", Height: "30 cm", Material: "ABS plastic", Accessories: "28 hands, web accessories" },
    stock: 5,
    reservedStock: 0,
    availableStock: 5,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ht-thor-endgame",
    name: "Hot Toys Thor (Avengers: Endgame) 1/6 Scale Figure",
    slug: "hot-toys-thor-avengers-endgame",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    salePrice: 34499,
    regularPrice: 37999,
    franchise: "marvel",
    brand: "hot-toys",
    tags: ["thor", "avengers", "endgame", "hot-toys", "1/6-scale"],
    description:
      "<p>Fat Thor in his Endgame attire — complete with Stormbreaker, Mjolnir, and power effects.</p>",
    specs: { Scale: "1/6", Height: "33 cm", Material: "ABS plastic" },
    stock: 3,
    reservedStock: 0,
    availableStock: 3,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Hot Toys / DC ──────────────────────────────────────────────────────────
  {
    id: "ht-batman-arkham-knight",
    name: "Hot Toys Batman (Arkham Knight) 1/6 Scale Figure",
    slug: "hot-toys-batman-arkham-knight",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 29999,
    regularPrice: 33999,
    franchise: "dc",
    brand: "hot-toys",
    tags: ["batman", "dc", "arkham", "hot-toys", "1/6-scale"],
    description:
      "<p>The Dark Knight's Arkham Knight armored suit in stunning sixth-scale detail. Includes LED glowing eyes and 10 batarangs.</p>",
    specs: { Scale: "1/6", Height: "31 cm", Material: "ABS plastic, fabric suit" },
    stock: 6,
    reservedStock: 0,
    availableStock: 6,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Iron Studios / Marvel ─────────────────────────────────────────────────
  {
    id: "is-black-panther-bg",
    name: "Iron Studios Black Panther Battle Diorama 1/10 Scale",
    slug: "iron-studios-black-panther-battle-diorama",
    images: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 8999,
    regularPrice: 9999,
    franchise: "marvel",
    brand: "iron-studios",
    tags: ["black-panther", "wakanda", "iron-studios", "1/10-scale", "statue"],
    description:
      "<p>T'Challa in his iconic Black Panther suit, cast in polystone resin with a Wakanda-inspired base.</p>",
    specs: { Scale: "1/10", Height: "22 cm", Material: "Polystone resin" },
    stock: 12,
    reservedStock: 0,
    availableStock: 12,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "is-captain-america-mcu",
    name: "Iron Studios Captain America Deluxe 1/10 Scale",
    slug: "iron-studios-captain-america-deluxe",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 7499,
    regularPrice: 8499,
    franchise: "marvel",
    brand: "iron-studios",
    tags: ["captain-america", "avengers", "iron-studios", "1/10-scale"],
    description: "<p>Steve Rogers mid-throw with his Vibranium shield. Based on Endgame design.</p>",
    specs: { Scale: "1/10", Height: "24 cm", Material: "Polystone resin" },
    stock: 15,
    reservedStock: 0,
    availableStock: 15,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 4,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Sideshow / DC ─────────────────────────────────────────────────────────
  {
    id: "ss-joker-premium",
    name: "Sideshow Joker Premium Format Figure",
    slug: "sideshow-joker-premium-format",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 74999,
    regularPrice: 82999,
    franchise: "dc",
    brand: "sideshow",
    tags: ["joker", "dc", "sideshow", "premium-format", "statue"],
    description:
      "<p>The Clown Prince of Crime stands over 56 cm in this iconic Premium Format collectible. Hand-finished polystone with fabric elements.</p>",
    specs: {
      Scale: "1/4",
      Height: "56 cm",
      Material: "Polystone, fabric, metal",
      "Edition Size": "1000",
    },
    stock: 2,
    reservedStock: 0,
    availableStock: 2,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 1,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ss-superman-premium",
    name: "Sideshow Superman Premium Format Figure",
    slug: "sideshow-superman-premium-format",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    salePrice: 84999,
    regularPrice: 94999,
    franchise: "dc",
    brand: "sideshow",
    tags: ["superman", "dc", "sideshow", "premium-format"],
    description:
      "<p>The Man of Steel mid-flight, sculpted in incredible detail. A centrepiece for any serious collection.</p>",
    specs: { Scale: "1/4", Height: "60 cm", Material: "Polystone, fabric" },
    stock: 0,
    reservedStock: 0,
    availableStock: 0,
    inStock: false,
    isPreorder: true,
    preorderShipDate: "Q3-2026",
    lowStockThreshold: 1,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Bandai / Anime ────────────────────────────────────────────────────────
  {
    id: "b-goku-shfiguarts",
    name: "Bandai S.H.Figuarts Son Goku -Fierce Battle-",
    slug: "bandai-shfiguarts-son-goku-fierce-battle",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 4999,
    regularPrice: 5499,
    franchise: "anime",
    brand: "bandai",
    tags: ["dragon-ball-z", "goku", "bandai", "shfiguarts", "anime"],
    description:
      "<p>Highly articulated S.H.Figuarts Goku with energy effect parts and swap-out faces. Perfect for dynamic display poses.</p>",
    specs: { Scale: "1/12", Height: "14 cm", Accessories: "3 faces, 10 hands, Kamehameha effect" },
    stock: 20,
    reservedStock: 0,
    availableStock: 20,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "b-tanjiro-shfiguarts",
    name: "Bandai S.H.Figuarts Tanjiro Kamado",
    slug: "bandai-shfiguarts-tanjiro-kamado",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 4499,
    regularPrice: 4999,
    franchise: "anime",
    brand: "bandai",
    tags: ["demon-slayer", "tanjiro", "bandai", "shfiguarts", "anime"],
    description: "<p>Tanjiro Kamado from Demon Slayer with Water Breathing effect parts. Features highly poseable joints.</p>",
    specs: { Scale: "1/12", Height: "15 cm", Accessories: "Water breathing effects, 2 faces" },
    stock: 18,
    reservedStock: 0,
    availableStock: 18,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "b-luffy-gear5-shfiguarts",
    name: "Bandai S.H.Figuarts Monkey D. Luffy (Gear 5)",
    slug: "bandai-shfiguarts-monkey-d-luffy-gear-5",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 5299,
    regularPrice: 5799,
    franchise: "anime",
    brand: "bandai",
    tags: ["one-piece", "luffy", "gear-5", "bandai", "shfiguarts"],
    description: "<p>Sun God Nika form — Luffy's Gear 5 transformation with fluffy white hair and laugh-powered effects.</p>",
    specs: { Scale: "1/12", Height: "16 cm", Accessories: "Smile effect parts, 3 swap faces" },
    stock: 10,
    reservedStock: 0,
    availableStock: 10,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── McFarlane / DC ────────────────────────────────────────────────────────
  {
    id: "mc-batman-three-jokers",
    name: "McFarlane Batman Three Jokers 7-inch Figure",
    slug: "mcfarlane-batman-three-jokers",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 2999,
    regularPrice: 3499,
    franchise: "dc",
    brand: "mcfarlane",
    tags: ["batman", "dc", "mcfarlane", "7-inch"],
    description: "<p>Batman in his classic Jim Lee-inspired armored suit from the Three Jokers storyline, with 22 points of articulation.</p>",
    specs: { Scale: "1/10 approx", Height: "18 cm", Accessories: "Batarang, display base" },
    stock: 25,
    reservedStock: 0,
    availableStock: 25,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "mc-spawn-classic",
    name: "McFarlane Spawn (Classic) 7-inch Figure",
    slug: "mcfarlane-spawn-classic",
    images: [
      "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    ],
    salePrice: 2499,
    regularPrice: 2999,
    franchise: "image-comics",
    brand: "mcfarlane",
    tags: ["spawn", "mcfarlane", "7-inch", "classic", "image-comics"],
    description: "<p>The original Spawn in his classic green-and-black suit. Todd McFarlane's iconic Image Comics creation in superb modern articulation.</p>",
    specs: { Scale: "1/10 approx", Height: "18 cm", Accessories: "Cape, chains" },
    stock: 30,
    reservedStock: 0,
    availableStock: 30,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 8,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── ThreeZero / Star Wars ─────────────────────────────────────────────────
  {
    id: "tz-mandalorian-16",
    name: "ThreeZero The Mandalorian DLX 1/6 Scale Figure",
    slug: "threezero-mandalorian-dlx",
    images: [
      "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    ],
    salePrice: 18999,
    regularPrice: 20999,
    franchise: "star-wars",
    brand: "threezero",
    tags: ["mandalorian", "star-wars", "threezero", "dlx", "1/6-scale"],
    description:
      "<p>Mando with Beskar armour and Grogu (Baby Yoda) in a knapsack. Stunning 1/6 scale collectible with LED eyes.</p>",
    specs: { Scale: "1/6", Height: "30 cm", Accessories: "Grogu figure, blaster, rifle, Beskar spear" },
    stock: 7,
    reservedStock: 0,
    availableStock: 7,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "tz-darth-vader-dlx",
    name: "ThreeZero Darth Vader DLX 1/6 Scale Figure",
    slug: "threezero-darth-vader-dlx",
    images: [
      "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    ],
    salePrice: 19999,
    regularPrice: 21999,
    franchise: "star-wars",
    brand: "threezero",
    tags: ["darth-vader", "star-wars", "threezero", "dlx"],
    description: "<p>The Dark Lord of the Sith in Beskar-accurate detail. Red LED lightsaber and multiple hand options.</p>",
    specs: { Scale: "1/6", Height: "34 cm", Accessories: "Lightsaber (LED), 6 interchangeable hands" },
    stock: 4,
    reservedStock: 0,
    availableStock: 4,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Sideshow / Marvel (high-end) ──────────────────────────────────────────
  {
    id: "ss-wolverine-legendary",
    name: "Sideshow Wolverine Legendary Scale Figure",
    slug: "sideshow-wolverine-legendary-scale",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 178999,
    regularPrice: 195999,
    franchise: "marvel",
    brand: "sideshow",
    tags: ["wolverine", "marvel", "sideshow", "legendary-scale", "statue"],
    description:
      "<p>Sideshow's largest-ever Wolverine at 1:2 scale — 68 cm of pure, clawed fury. Limited edition of 750.</p>",
    specs: {
      Scale: "1/2",
      Height: "68 cm",
      Material: "Polystone, metal claws",
      "Edition Size": "750",
    },
    stock: 1,
    reservedStock: 0,
    availableStock: 1,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 1,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Bandai / Anime (Preorder) ─────────────────────────────────────────────
  {
    id: "b-naruto-rikudo-shfiguarts",
    name: "Bandai S.H.Figuarts Naruto (Rikudō Sennin Mode)",
    slug: "bandai-shfiguarts-naruto-rikudo-sennin-mode",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 5799,
    regularPrice: 6299,
    franchise: "anime",
    brand: "bandai",
    tags: ["naruto", "sage-mode", "bandai", "shfiguarts", "preorder"],
    description: "<p>Naruto in his most powerful form — Six Paths Sage Mode — with Truth-Seeking Orbs and Tailed Beast effects.</p>",
    specs: { Scale: "1/12", Height: "15 cm", Accessories: "Energy effects, 3 faces" },
    stock: 0,
    reservedStock: 0,
    availableStock: 0,
    inStock: false,
    isPreorder: true,
    preorderShipDate: "Q4-2026",
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "is-thanos-bds",
    name: "Iron Studios Thanos BDS Art Scale 1/10",
    slug: "iron-studios-thanos-bds-art-scale",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    salePrice: 9499,
    regularPrice: 10499,
    franchise: "marvel",
    brand: "iron-studios",
    tags: ["thanos", "avengers", "infinity-gauntlet", "iron-studios"],
    description: "<p>The Mad Titan holding the completed Infinity Gauntlet. Polystone diorama base featuring Titan rubble.</p>",
    specs: { Scale: "1/10", Height: "28 cm", Material: "Polystone resin" },
    stock: 9,
    reservedStock: 0,
    availableStock: 9,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Hot Toys / Terminator ─────────────────────────────────────────────────
  {
    id: "ht-t800-battle-damaged-v2",
    name: "T-800 (Battle Damaged Version 2.0) Sixth Scale Figure by Hot Toys",
    slug: "hot-toys-t800-battle-damaged-v2",
    images: [
      "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    ],
    salePrice: 42999,
    regularPrice: 47999,
    franchise: "terminator",
    brand: "hot-toys",
    tags: ["terminator", "t-800", "hot-toys", "1/6-scale", "battle-damaged"],
    description:
      "<p>The iconic T-800 in battle-damaged glory — chrome endoskeleton exposed, LED eye, fully articulated. Features interchangeable battle-damage arm and torso panels.</p><ul><li>Approx. 33 cm tall</li><li>LED light-up eye</li><li>Die-cast frame parts</li></ul>",
    specs: {
      Scale: "1/6",
      Height: "33 cm",
      Material: "ABS, Die-cast",
      Accessories: "Shotgun, Minigun, 10 hands",
      "LED Features": "Yes",
    },
    stock: 4,
    reservedStock: 0,
    availableStock: 4,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Hot Toys / Marvel ──────────────────────────────────────────────────────
  {
    id: "ht-wolverine-deluxe",
    name: "WOLVERINE (Deluxe Version) Sixth Scale Figure by Hot Toys",
    slug: "hot-toys-wolverine-deluxe-version",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 49999,
    regularPrice: 54999,
    franchise: "marvel",
    brand: "hot-toys",
    tags: ["wolverine", "x-men", "hot-toys", "1/6-scale", "deluxe"],
    description:
      "<p>Logan in his yellow-and-blue classic X-Men suit. Deluxe version includes unmasked head sculpt, berserker rage hands, and display base.</p>",
    specs: {
      Scale: "1/6",
      Height: "30 cm",
      Material: "ABS plastic, fabric suit",
      Accessories: "2 head sculpts, 8 hands, display base",
    },
    stock: 3,
    reservedStock: 0,
    availableStock: 3,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ht-tony-stark-mech-test-dlx",
    name: "Tony Stark Mech Test Version Deluxe 1/6 Scale Figure by Hot Toys",
    slug: "hot-toys-tony-stark-mech-test-version-deluxe",
    images: [
      "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
    ],
    salePrice: 25999,
    regularPrice: 34999,
    franchise: "marvel",
    brand: "hot-toys",
    tags: ["iron-man", "tony-stark", "hot-toys", "1/6-scale", "deluxe"],
    description:
      "<p>Tony Stark in his workshop attire putting on the Iron Man gauntlet. Highly detailed head sculpt with exclusive workshop backdrop display stand.</p>",
    specs: {
      Scale: "1/6",
      Height: "31 cm",
      Material: "ABS plastic, fabric",
      Accessories: "Gauntlet, arc reactor, tools",
    },
    stock: 5,
    reservedStock: 0,
    availableStock: 5,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Hot Toys / DC ──────────────────────────────────────────────────────────
  {
    id: "ht-batman-returns-dlx",
    name: "BATMAN (Batman Returns) Deluxe Version Sixth Scale Figure by Hot Toys",
    slug: "hot-toys-batman-batman-returns-deluxe",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 43999,
    regularPrice: 45999,
    franchise: "dc",
    brand: "hot-toys",
    tags: ["batman", "dc", "batman-returns", "hot-toys", "1/6-scale", "deluxe"],
    description:
      "<p>The Dark Knight from Batman Returns (1992) — Tim Burton's iconic costume faithfully recreated with the Bat-Signal grapple and cape in premium fabric.</p>",
    specs: {
      Scale: "1/6",
      Height: "31 cm",
      Material: "ABS plastic, fabric cape",
      Accessories: "Grapple gun, Batarangs, display stand",
    },
    stock: 6,
    reservedStock: 0,
    availableStock: 6,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Hasbro / Marvel ───────────────────────────────────────────────────────
  {
    id: "ml-deadpool-legacy",
    name: "Marvel Legends Series Deadpool (Legacy)",
    slug: "marvel-legends-deadpool-legacy",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 3999,
    franchise: "marvel",
    brand: "hasbro",
    tags: ["deadpool", "marvel", "marvel-legends", "hasbro", "6-inch"],
    description: "<p>Wade Wilson in his red-and-black mercenary suit — 6-inch Marvel Legends with 14 articulation points and katanas.</p>",
    specs: { Scale: "1/12 approx", Height: "16 cm", Accessories: "2 katanas, pistols, chimichangas" },
    stock: 0,
    reservedStock: 0,
    availableStock: 0,
    inStock: false,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ml-ghost-rider-danny-ketch",
    name: "Marvel Legends Ghost Rider (Danny Ketch) — Marvel 85th Anniversary",
    slug: "marvel-legends-ghost-rider-danny-ketch",
    images: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 7999,
    regularPrice: 8499,
    franchise: "marvel",
    brand: "hasbro",
    tags: ["ghost-rider", "marvel", "marvel-legends", "hasbro", "6-inch", "85th-anniversary"],
    description: "<p>Danny Ketch as Ghost Rider from the 85th Anniversary Comics wave — with hellfire chain and flame effects.</p>",
    specs: { Scale: "1/12 approx", Height: "16 cm", Accessories: "Hellfire chain, flame effects" },
    stock: 12,
    reservedStock: 0,
    availableStock: 12,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ml-wolverine-legacy",
    name: "Marvel Legends Series Wolverine (Legacy)",
    slug: "marvel-legends-wolverine-legacy",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 3899,
    regularPrice: 3999,
    franchise: "marvel",
    brand: "hasbro",
    tags: ["wolverine", "x-men", "marvel-legends", "hasbro", "6-inch"],
    description: "<p>Logan in his brown-and-tan Wolverine suit — Marvel Legends 6-inch with retractable claws and multiple hands.</p>",
    specs: { Scale: "1/12 approx", Height: "16 cm", Accessories: "Unmasked head, 3 sets of hands" },
    stock: 8,
    reservedStock: 0,
    availableStock: 8,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ml-deadpool-and-wolverine-deadpool",
    name: "Marvel Legends Deadpool (Deadpool & Wolverine)",
    slug: "marvel-legends-deadpool-and-wolverine-deadpool",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 3699,
    regularPrice: 4599,
    franchise: "marvel",
    brand: "hasbro",
    tags: ["deadpool", "marvel-legends", "hasbro", "deadpool-wolverine", "6-inch"],
    description: "<p>Deadpool from the MCU Deadpool & Wolverine film — Marvel Legends 6-inch with updated movie-accurate suit.</p>",
    specs: { Scale: "1/12 approx", Height: "16 cm", Accessories: "Katanas, pistols" },
    stock: 15,
    reservedStock: 0,
    availableStock: 15,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "ml-max-series-hulk",
    name: "Marvel Legends Maximum Series Hulk Action Figure",
    slug: "marvel-legends-maximum-series-hulk",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    ],
    salePrice: 8999,
    regularPrice: 9999,
    franchise: "marvel",
    brand: "hasbro",
    tags: ["hulk", "marvel-legends", "hasbro", "maximum-series", "oversized"],
    description: "<p>The Incredible Hulk in the Maximum Series — 10-inch oversized figure with rage-smash hands and incredible detail.</p>",
    specs: { Scale: "Oversized", Height: "25 cm", Accessories: "5 interchangeable hands" },
    stock: 10,
    reservedStock: 0,
    availableStock: 10,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Hasbro / G.I. Joe ────────────────────────────────────────────────────
  {
    id: "gij-sgt-slaughter",
    name: "G.I. Joe Classified Series #129, Mad Marauders Sgt. Slaughter",
    slug: "gi-joe-classified-sgt-slaughter",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 5499,
    franchise: "gi-joe",
    brand: "hasbro",
    tags: ["gi-joe", "sgt-slaughter", "classified-series", "hasbro", "6-inch"],
    description: "<p>The legendary Sgt. Slaughter in the G.I. Joe Classified Series – Mad Marauders edition with premium detail and accessories.</p>",
    specs: { Scale: "1/12 approx", Height: "16 cm", Accessories: "Baton, pistol, rifle, helmet" },
    stock: 18,
    reservedStock: 0,
    availableStock: 18,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "gij-shipwreck",
    name: "G.I. Joe Classified Series Shipwreck Action Figure",
    slug: "gi-joe-classified-shipwreck",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 4299,
    franchise: "gi-joe",
    brand: "hasbro",
    tags: ["gi-joe", "shipwreck", "classified-series", "hasbro", "6-inch"],
    description: "<p>Sailor Etienne R. Alcazar — G.I. Joe's Shipwreck in the Classified Series with Polly the parrot companion.</p>",
    specs: { Scale: "1/12 approx", Height: "16 cm", Accessories: "Pistol, harpoon, Polly parrot" },
    stock: 20,
    reservedStock: 0,
    availableStock: 20,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Mattel / Masters of the Universe ──────────────────────────────────────
  {
    id: "motu-he-man-40th-masterverse",
    name: "Masters of the Universe Masterverse He-Man 40th Anniversary Action Figure",
    slug: "motu-masterverse-he-man-40th-anniversary",
    images: [
      "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 4399,
    franchise: "masters-of-the-universe",
    brand: "mattel",
    tags: ["he-man", "motu", "masterverse", "40th-anniversary", "7-inch"],
    description: "<p>The Most Powerful Man in the Universe celebrates 40 years in the Masterverse line — with Power Sword, Battle Axe, and Shield.</p>",
    specs: { Scale: "1/10 approx", Height: "18 cm", Accessories: "Power Sword, Battle Axe, Shield" },
    stock: 22,
    reservedStock: 0,
    availableStock: 22,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── ThreeZero / Transformers ──────────────────────────────────────────────
  {
    id: "tz-transformers-mdlx-megatron",
    name: "Transformers MDLX Megatron By ThreeZero",
    slug: "threezero-transformers-mdlx-megatron",
    images: [
      "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
    ],
    salePrice: 11999,
    regularPrice: 12999,
    franchise: "transformers",
    brand: "threezero",
    tags: ["megatron", "transformers", "threezero", "mdlx", "g1"],
    description: "<p>G1 Megatron in the MDLX pocket-scale format — die-cast construction with LED eyes, transformable joints, and fusion cannon.</p>",
    specs: { Scale: "MDLX", Height: "20 cm", Material: "Die-cast, ABS", Accessories: "Fusion cannon, 6 hands" },
    stock: 14,
    reservedStock: 0,
    availableStock: 14,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "tz-transformers-rotf-dlx-megatron",
    name: "Transformers: Revenge of the Fallen DLX Megatron By ThreeZero",
    slug: "threezero-transformers-rotf-dlx-megatron",
    images: [
      "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
    ],
    salePrice: 39999,
    regularPrice: 41999,
    franchise: "transformers",
    brand: "threezero",
    tags: ["megatron", "transformers", "threezero", "dlx", "rotf"],
    description: "<p>Revenge of the Fallen movie Megatron in massive 1/6 scale DLX format — full die-cast construction, LED eyes, flight mode display stand.</p>",
    specs: { Scale: "1/6", Height: "40 cm", Material: "Die-cast, ABS", Accessories: "LED cannon, display stand" },
    stock: 3,
    reservedStock: 0,
    availableStock: 3,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 1,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "tz-transformers-rotb-dlx-bumblebee",
    name: "Transformers: Rise of the Beasts DLX Bumblebee By ThreeZero",
    slug: "threezero-transformers-rotb-dlx-bumblebee",
    images: [
      "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
    ],
    salePrice: 25999,
    regularPrice: 27999,
    franchise: "transformers",
    brand: "threezero",
    tags: ["bumblebee", "transformers", "threezero", "dlx", "rotb"],
    description: "<p>Rise of the Beasts Bumblebee in 1/6 DLX scale — iconic yellow with LED headlights and battle damage panels.</p>",
    specs: { Scale: "1/6", Height: "30 cm", Material: "Die-cast, ABS", Accessories: "Plasma cannon, battle pieces" },
    stock: 5,
    reservedStock: 0,
    availableStock: 5,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── McFarlane / DC & Warhammer ────────────────────────────────────────────
  {
    id: "mc-aquaman-page-punchers",
    name: "Aquaman (DC Page Punchers) Figure By McFarlane",
    slug: "mcfarlane-aquaman-dc-page-punchers",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 4599,
    franchise: "dc",
    brand: "mcfarlane",
    tags: ["aquaman", "dc", "mcfarlane", "page-punchers"],
    description: "<p>Arthur Curry as Aquaman — DC Page Punchers 7-inch figure with Aquaman Universe issue comic book.</p>",
    specs: { Scale: "1/10 approx", Height: "18 cm", Accessories: "Trident, comic book" },
    stock: 30,
    reservedStock: 0,
    availableStock: 30,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 8,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "mc-eliminator-warhammer",
    name: "Eliminator: Space Marine (Warhammer 40,000) Figure",
    slug: "mcfarlane-eliminator-space-marine-warhammer",
    images: [
      "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    ],
    salePrice: 4799,
    regularPrice: 4999,
    franchise: "warhammer",
    brand: "mcfarlane",
    tags: ["warhammer", "space-marine", "eliminator", "mcfarlane"],
    description: "<p>Eliminator Space Marine from Warhammer 40K — McFarlane's premium 7-inch figure with sniper rifle and detailed armour deco.</p>",
    specs: { Scale: "1/10 approx", Height: "18 cm", Accessories: "Sniper rifle, display base" },
    stock: 16,
    reservedStock: 0,
    availableStock: 16,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 4,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Mezco / Marvel & DC ───────────────────────────────────────────────────
  {
    id: "mez-batman-animated-one12",
    name: "Batman: The Animated Series Batman One:12 Collective Action Figure",
    slug: "mezco-batman-animated-series-one12",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 14999,
    regularPrice: 16999,
    franchise: "dc",
    brand: "mezco",
    tags: ["batman", "dc", "animated-series", "mezco", "one-12-collective"],
    description: "<p>Batman from the beloved animated series — Mezco One:12 Collective with soft-goods fabric cape, 12 action expressions, grapple gun, and Batarangs.</p>",
    specs: { Scale: "1/12", Height: "16 cm", Material: "Plastic, soft-goods fabric", Accessories: "14+ accessories" },
    stock: 7,
    reservedStock: 0,
    availableStock: 7,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "mez-thor-mighty-one12",
    name: "The Mighty Thor One:12 Collective Action Figure",
    slug: "mezco-mighty-thor-one12",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    salePrice: 13999,
    regularPrice: 14999,
    franchise: "marvel",
    brand: "mezco",
    tags: ["thor", "marvel", "mezco", "one-12-collective"],
    description: "<p>The Odinson in his classic hammer-wielding glory — Mezco One:12 Collective with soft-goods cape, Mjolnir with lightning effects.</p>",
    specs: { Scale: "1/12", Height: "16 cm", Material: "Plastic, soft-goods", Accessories: "Mjolnir, lightning, 3 head sculpts" },
    stock: 9,
    reservedStock: 0,
    availableStock: 9,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── NECA / Horror & Terminator ────────────────────────────────────────────
  {
    id: "neca-freddy-krueger-elm3",
    name: "A Nightmare on Elm Street 3: Dream Warriors Freddy Krueger Ultimate Figure by NECA",
    slug: "neca-freddy-krueger-nightmare-elm-street-3",
    images: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 5599,
    regularPrice: 6499,
    franchise: "horror",
    brand: "neca",
    tags: ["freddy-krueger", "nightmare", "neca", "ultimate", "horror"],
    description: "<p>Freddy Krueger from Dream Warriors — NECA Ultimate 7-inch with striped sweater, glove, multiple heads, and diorama accessories.</p>",
    specs: { Scale: "Ultimate (7\")", Height: "18 cm", Accessories: "3 heads, 4 hand sets, glove" },
    stock: 11,
    reservedStock: 0,
    availableStock: 11,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Kaiyodo / Attack on Titan ─────────────────────────────────────────────
  {
    id: "ky-aot-beast-titan-revoltech",
    name: "Attack on Titan Amazing Yamaguchi Revoltech NR097 Beast Titan Action Figure",
    slug: "kaiyodo-aot-beast-titan-revoltech-nr097",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 10999,
    regularPrice: 11999,
    franchise: "anime",
    brand: "kaiyodo",
    tags: ["attack-on-titan", "beast-titan", "revoltech", "kaiyodo", "anime"],
    description: "<p>Zeke Yeager's Beast Titan in the Amazing Yamaguchi Revoltech series — full articulation with multiple joint systems for ultra-dynamic poses.</p>",
    specs: { Scale: "N/A (oversized)", Height: "28 cm", Accessories: "Rock effects, 4 expression parts" },
    stock: 6,
    reservedStock: 0,
    availableStock: 6,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Bandai / Anime (Chainsaw Man) ─────────────────────────────────────────
  {
    id: "b-chainsaw-man-vibration-stars",
    name: "Chainsaw Man Vibration Stars Chainsaw Man Figure",
    slug: "bandai-chainsaw-man-vibration-stars",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 2399,
    regularPrice: 3999,
    franchise: "anime",
    brand: "bandai",
    tags: ["chainsaw-man", "denji", "bandai", "vibration-stars", "anime"],
    description: "<p>Denji as the Chainsaw Devil — Bandai Vibration Stars dynamic statue figure in iconic battle pose.</p>",
    specs: { Height: "20 cm", Material: "PVC/ABS" },
    stock: 14,
    reservedStock: 0,
    availableStock: 14,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 4,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "b-bruce-lee-legacy-shfiguarts",
    name: "Bruce Lee Legacy 50th Version Action Figure By S.H.Figuarts",
    slug: "bandai-shfiguarts-bruce-lee-legacy-50th",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 7999,
    regularPrice: 9999,
    franchise: "anime",
    brand: "bandai",
    tags: ["bruce-lee", "bandai", "shfiguarts", "legacy", "50th"],
    description: "<p>Bruce Lee's iconic yellow tracksuit from Game of Death — S.H.Figuarts 50th anniversary edition with nunchaku and swap faces.</p>",
    specs: { Scale: "1/12", Height: "15 cm", Accessories: "Nunchaku, 3 faces, 10 hands" },
    stock: 8,
    reservedStock: 0,
    availableStock: 8,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Prime 1 Studio ────────────────────────────────────────────────────────
  {
    id: "p1s-matrix-neo-bonus",
    name: "The Matrix (Film) Neo Bonus Version By Prime 1 Studio",
    slug: "prime-1-studio-the-matrix-neo-bonus",
    images: [
      "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    ],
    salePrice: 178999,
    regularPrice: 189999,
    franchise: "sci-fi",
    brand: "prime-1-studio",
    tags: ["matrix", "neo", "prime-1-studio", "museum-quality", "statue"],
    description:
      "<p>Thomas Anderson as Neo in the Bullet-Dodge scene — Prime 1 Studio's life-size environment presentation with 150+ bullet effects and LED backdrop at 1:3 scale.</p>",
    specs: {
      Scale: "1/3",
      Height: "85 cm",
      Material: "Polystone, LED",
      "Edition Size": "Limited",
      Accessories: "150 bullet effects, 2 Neo portraits",
    },
    stock: 1,
    reservedStock: 0,
    availableStock: 1,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 1,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── InArt / DC ────────────────────────────────────────────────────────────
  {
    id: "ia-batman-dark-knight-rises-112",
    name: "Batman (The Dark Knight Rises) Deluxe 1/12 Collectible Figure by INART",
    slug: "inart-batman-dark-knight-rises-deluxe-112",
    images: [
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    ],
    salePrice: 10999,
    regularPrice: 10999,
    franchise: "dc",
    brand: "inart",
    tags: ["batman", "dc", "dark-knight-rises", "inart", "1/12"],
    description: "<p>Christian Bale as Batman from The Dark Knight Rises — InArt silicone-skin portrait with fabric suit, full gear, and urban Gotham display.</p>",
    specs: { Scale: "1/12", Height: "17 cm", Material: "Silicone, fabric, resin", Accessories: "Grapple, Batarangs, 2 portraits" },
    stock: 5,
    reservedStock: 0,
    availableStock: 5,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 2,
    isFeatured: true,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── InArt / Harry Potter ──────────────────────────────────────────────────
  {
    id: "ia-hp-draco-malfoy-16-dlx",
    name: "Harry Potter and the Philosopher's Stone INART Draco Malfoy 1/6 Scale Deluxe Edition",
    slug: "inart-harry-potter-draco-malfoy-16-deluxe",
    images: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 59999,
    regularPrice: 69999,
    franchise: "harry-potter",
    brand: "inart",
    tags: ["harry-potter", "draco-malfoy", "inart", "1/6-scale", "deluxe"],
    description:
      "<p>Draco Malfoy in his Hogwarts school uniform — InArt 1/6 scale Deluxe with silicone portrait, wand, Quidditch outfit swap, and Great Hall backdrop.</p>",
    specs: {
      Scale: "1/6",
      Height: "28 cm",
      Material: "Silicone, fabric, resin",
      Accessories: "2 portraits, wand, Quidditch helmet, broom",
    },
    stock: 4,
    reservedStock: 0,
    availableStock: 4,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 1,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── NECA / TMNT ─────────────────────────────────────────────────────────
  {
    id: "neca-tmnt-leonardo-classic-ultimate",
    name: "NECA TMNT Leonardo (Classic Cartoon) Ultimate Action Figure",
    slug: "neca-tmnt-leonardo-classic-cartoon-ultimate",
    images: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 4999,
    regularPrice: 5999,
    franchise: "tmnt",
    brand: "neca",
    tags: ["tmnt", "leonardo", "neca", "ultimate", "classic-cartoon"],
    description: "<p>Leonardo in his classic 1987 animated series deco — NECA Ultimate 7-inch with 25 points of articulation, 2 katanas, swappable heads, and pizza slice accessory.</p>",
    specs: { Scale: "Ultimate (7\")", Height: "18 cm", Accessories: "2 katanas, 2 heads, pizza, sewer manhole base" },
    stock: 14,
    reservedStock: 0,
    availableStock: 14,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 4,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "neca-tmnt-raphael-classic-ultimate",
    name: "NECA TMNT Raphael (Classic Cartoon) Ultimate Action Figure",
    slug: "neca-tmnt-raphael-classic-cartoon-ultimate",
    images: [
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    ],
    salePrice: 4999,
    regularPrice: 5999,
    franchise: "tmnt",
    brand: "neca",
    tags: ["tmnt", "raphael", "neca", "ultimate", "classic-cartoon"],
    description: "<p>Raphael in his classic 1987 animated series deco — NECA Ultimate 7-inch with sai weapons, swappable angry and smirking heads, and diorama sewer base.</p>",
    specs: { Scale: "Ultimate (7\")", Height: "18 cm", Accessories: "2 sai, 2 heads, sewer base" },
    stock: 12,
    reservedStock: 0,
    availableStock: 12,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 4,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Bandai / Jujutsu Kaisen ───────────────────────────────────────────────
  {
    id: "b-gojo-satoru-jjk-shfiguarts",
    name: "Bandai S.H.Figuarts Gojo Satoru (Jujutsu Kaisen)",
    slug: "bandai-shfiguarts-gojo-satoru-jujutsu-kaisen",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 6999,
    regularPrice: 7499,
    franchise: "jujutsu-kaisen",
    brand: "bandai",
    tags: ["jujutsu-kaisen", "gojo", "bandai", "shfiguarts", "anime"],
    description: "<p>Satoru Gojo — the most powerful jujutsu sorcerer — in S.H.Figuarts quality. Includes Infinity effect parts, blindfolded and revealed heads, and Domain Expansion hand poses.</p>",
    specs: { Scale: "1/12", Height: "16 cm", Accessories: "2 heads, Infinity effects, 10 expression hands" },
    stock: 10,
    reservedStock: 0,
    availableStock: 10,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 3,
    isFeatured: true,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "b-yuji-itadori-jjk-shfiguarts",
    name: "Bandai S.H.Figuarts Yuji Itadori (Jujutsu Kaisen)",
    slug: "bandai-shfiguarts-yuji-itadori-jujutsu-kaisen",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 5999,
    regularPrice: 6499,
    franchise: "jujutsu-kaisen",
    brand: "bandai",
    tags: ["jujutsu-kaisen", "itadori", "yuji", "bandai", "shfiguarts", "anime"],
    description: "<p>Yuji Itadori with Divergent Fist and Black Flash effect parts — S.H.Figuarts JJK debut figure. Features event-exclusive Sukuna expression face.</p>",
    specs: { Scale: "1/12", Height: "15 cm", Accessories: "3 faces, punch effects, 8 hands" },
    stock: 15,
    reservedStock: 0,
    availableStock: 15,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 4,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── McFarlane / Game of Thrones ───────────────────────────────────────────
  {
    id: "mc-jon-snow-got-7inch",
    name: "McFarlane Toys Game of Thrones Jon Snow 7-inch Figure",
    slug: "mcfarlane-game-of-thrones-jon-snow",
    images: [
      "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 4499,
    franchise: "game-of-thrones",
    brand: "mcfarlane",
    tags: ["game-of-thrones", "jon-snow", "mcfarlane", "7-inch", "got"],
    description: "<p>Jon Snow, Lord Commander of the Night's Watch, in his black fur cloak from the Wall. McFarlane 7-inch with Longclaw Valyrian steel sword and 22 articulation points.</p>",
    specs: { Scale: "1/10 approx", Height: "18 cm", Accessories: "Longclaw sword, Night's Watch cloak" },
    stock: 20,
    reservedStock: 0,
    availableStock: 20,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
  {
    id: "mc-daenerys-targaryen-got-7inch",
    name: "McFarlane Toys Game of Thrones Daenerys Targaryen 7-inch Figure",
    slug: "mcfarlane-game-of-thrones-daenerys-targaryen",
    images: [
      "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    ],
    salePrice: 3999,
    regularPrice: 4499,
    franchise: "game-of-thrones",
    brand: "mcfarlane",
    tags: ["game-of-thrones", "daenerys", "targaryen", "mcfarlane", "7-inch", "got"],
    description: "<p>Daenerys Targaryen, Mother of Dragons, in her Dragonstone armour. McFarlane 7-inch with Dragonscale cloak, dragon egg accessory, and 20 points of articulation.</p>",
    specs: { Scale: "1/10 approx", Height: "17 cm", Accessories: "Dragon egg, display base" },
    stock: 18,
    reservedStock: 0,
    availableStock: 18,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: false,
    active: true,
    videos: [],
    restockHistory: [],
  },
  // ── Funko / Marvel ────────────────────────────────────────────────────────
  {
    id: "fn-deadpool-wolverine-photo-exclusive",
    name: "Deadpool with Wolverine Photo Exclusive Funko Pop!",
    slug: "funko-pop-deadpool-with-wolverine-photo-exclusive",
    images: [
      "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    ],
    salePrice: 3499,
    regularPrice: 3899,
    franchise: "marvel",
    brand: "funko",
    tags: ["deadpool", "wolverine", "funko-pop", "exclusive", "marvel"],
    description: "<p>Deadpool and Wolverine in a buddy-comedy photo pose — Funko Pop! Exclusive with premium photo card insert.</p>",
    specs: { Height: "9 cm", Material: "Vinyl" },
    stock: 25,
    reservedStock: 0,
    availableStock: 25,
    inStock: true,
    isPreorder: false,
    lowStockThreshold: 8,
    isFeatured: false,
    isBestseller: true,
    active: true,
    videos: [],
    restockHistory: [],
  },
];

// ─── Banners ──────────────────────────────────────────────────────────────────

export const SEED_BANNERS = [
  {
    id: "banner-001",
    title: "New Arrivals: Hot Toys 2026",
    subtitle: "Explore The Latest 1/6 Scale Masterpieces",
    ctaLabel: "Shop Now",
    ctaUrl: "/collections/hot-toys",
    backgroundImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=1600&q=80",
    backgroundColor: "#1a1a2e",
    textColor: "#ffffff",
    sortOrder: 1,
    active: true,
  },
  {
    id: "banner-002",
    title: "Iron Studios Battle Dioramas",
    subtitle: "Museum-quality polystone statues from ₹6,999",
    ctaLabel: "Browse Collection",
    ctaUrl: "/collections/iron-studios",
    backgroundImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1600&q=80",
    backgroundColor: "#2d1b69",
    textColor: "#ffffff",
    sortOrder: 2,
    active: true,
  },
  {
    id: "banner-003",
    title: "Pre-Order Now: Sideshow Superman",
    subtitle: "Limited edition. Secure yours before it sells out.",
    ctaLabel: "Pre-Order",
    ctaUrl: "/products/sideshow-superman-premium-format",
    backgroundImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80",
    backgroundColor: "#0d47a1",
    textColor: "#ffffff",
    sortOrder: 3,
    active: true,
  },
];

// ─── Promo Banners ────────────────────────────────────────────────────────────

export const SEED_PROMO_BANNERS = [
  {
    id: "promo-001",
    title: "Hot Toys Exclusives",
    ctaLabel: "Shop Hot Toys",
    ctaUrl: "/collections/hot-toys",
    image: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=600&q=80",
    sortOrder: 1,
    active: true,
  },
  {
    id: "promo-002",
    title: "Anime Figures",
    ctaLabel: "Browse Anime",
    ctaUrl: "/collections/anime",
    image: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=600&q=80",
    sortOrder: 2,
    active: true,
  },
  {
    id: "promo-003",
    title: "Star Wars Collection",
    ctaLabel: "Explore",
    ctaUrl: "/collections/star-wars",
    image: "https://images.unsplash.com/photo-1563656157432-67560011e209?w=600&q=80",
    sortOrder: 3,
    active: true,
  },
  {
    id: "promo-004",
    title: "DC Universe",
    ctaLabel: "Shop DC",
    ctaUrl: "/collections/dc",
    image: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=600&q=80",
    sortOrder: 4,
    active: true,
  },
];

// ─── Trust Badges ─────────────────────────────────────────────────────────────

export const SEED_TRUST_BADGES = [
  {
    id: "badge-shipping",
    title: "Free Shipping",
    sub: "On orders above ₹2,999",
    iconKey: "shipping" as const,
    sortOrder: 1,
    active: true,
  },
  {
    id: "badge-support",
    title: "Expert Support",
    sub: "Mon – Sat, 10 AM – 7 PM",
    iconKey: "support" as const,
    sortOrder: 2,
    active: true,
  },
  {
    id: "badge-rewards",
    title: "Loyalty Rewards",
    sub: "Earn points on every order",
    iconKey: "rewards" as const,
    sortOrder: 3,
    active: true,
  },
  {
    id: "badge-secure",
    title: "Secure Payments",
    sub: "UPI · Cards · EMI available",
    iconKey: "secure" as const,
    sortOrder: 4,
    active: true,
  },
];

// ─── Home Sections ────────────────────────────────────────────────────────────

export const SEED_HOME_SECTIONS = [
  {
    id: "home-featured",
    title: "Featured Products",
    subtitle: "Handpicked by our team",
    type: "featured" as const,
    itemLimit: 8,
    sortOrder: 1,
    active: true,
  },
  {
    id: "home-bestsellers",
    title: "Bestsellers",
    subtitle: "What everyone's buying",
    type: "bestseller" as const,
    itemLimit: 8,
    sortOrder: 2,
    active: true,
  },
  {
    id: "home-new-arrivals",
    title: "New Arrivals",
    subtitle: "Just landed",
    type: "new-arrivals" as const,
    itemLimit: 8,
    sortOrder: 3,
    active: true,
  },
  {
    id: "home-anime",
    title: "Anime Spotlight",
    collectionSlug: "anime",
    type: "custom" as const,
    itemLimit: 6,
    sortOrder: 4,
    active: true,
  },
];

// ─── Announcements ────────────────────────────────────────────────────────────

export const SEED_ANNOUNCEMENTS = [
  {
    id: "ann-001",
    message: "NO COST EMI ON ORDERS ABOVE ₹6,000 — Use code NOCOSTEMI at checkout",
    link: "/products",
    linkLabel: "Shop now",
    active: true,
    sortOrder: 1,
    bgColor: "#b91c1c",
    textColor: "#ffffff",
  },
  {
    id: "ann-002",
    message: "Hobson Bengaluru Store Now Open! Visit us at Indiranagar 100 Ft Road",
    link: "/policies/contact",
    linkLabel: "Get directions",
    active: true,
    sortOrder: 2,
    bgColor: "#1e40af",
    textColor: "#ffffff",
  },
  {
    id: "ann-003",
    message: "Pre-order Sideshow Superman Premium Format — Ships Q3 2026",
    link: "/products/sideshow-superman-premium-format",
    linkLabel: "Pre-order",
    active: true,
    sortOrder: 3,
    bgColor: "#065f46",
    textColor: "#ffffff",
  },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────

export const SEED_TESTIMONIALS = [
  {
    id: "t-001",
    name: "Arjun Mehta",
    rating: 5 as const,
    text: "Received my Hot Toys Iron Man perfectly packaged. The quality is phenomenal — Hobson is the only place I trust for high-end collectibles in India.",
    featured: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "t-002",
    name: "Priya Sharma",
    rating: 5 as const,
    text: "Ordered three Iron Studios statues and every single one arrived flawless. Their team answered all my questions within hours. Highly recommend!",
    featured: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "t-003",
    name: "Karthik Nair",
    rating: 4 as const,
    text: "Great range of Bandai S.H.Figuarts at competitive prices. Shipping was fast and secure. Will definitely be ordering again.",
    featured: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "t-004",
    name: "Divya Krishnan",
    rating: 5 as const,
    text: "The Sideshow Joker exceeded my expectations. Hobson's authentication guarantee gives you peace of mind when spending big.",
    featured: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "t-005",
    name: "Rohit Gupta",
    rating: 5 as const,
    text: "Best collectibles store in India, period. The Bengaluru store staff was incredibly knowledgeable and helped me pick the perfect piece.",
    featured: false,
    sortOrder: 5,
    active: true,
  },
  {
    id: "t-006",
    name: "Sanjay Mehra",
    rating: 5 as const,
    text: "I used to ship myself directly from outside the country but shipping was a mess. Then I found Hobson and it became much easier. Now it's my one-stop shop for all collectibles.",
    featured: true,
    sortOrder: 6,
    active: true,
  },
  {
    id: "t-007",
    name: "Pranav Kumar",
    rating: 5 as const,
    text: "Buying Iron Studios and Hot Toys figures from Hobson is always a pleasure. They maintain open communication even during import delays. Highly recommended.",
    featured: false,
    sortOrder: 7,
    active: true,
  },
  {
    id: "t-008",
    name: "Vivek Prabhu",
    rating: 5 as const,
    text: "Great prices, speedy delivery, and a vast range of collectibles. The packaging is excellent — I have always received my figures in mint condition.",
    featured: false,
    sortOrder: 8,
    active: true,
  },
];

// ─── FAQ ──────────────────────────────────────────────────────────────────────

export const SEED_FAQ = [
  {
    id: "faq-001",
    question: "Are all products 100% authentic?",
    answer: "Yes. Hobson Collectibles is an authorised dealer for all brands we carry. Every product comes with the manufacturer's original packaging and certificate of authenticity where applicable.",
    sortOrder: 1,
    active: true,
  },
  {
    id: "faq-002",
    question: "Do you ship across India?",
    answer: "We ship to all serviceable pin codes across India. Orders above ₹2,999 qualify for free standard shipping. Express delivery options are available at checkout.",
    sortOrder: 2,
    active: true,
  },
  {
    id: "faq-003",
    question: "What is your return/exchange policy?",
    answer: "We accept returns within 7 days of delivery for items in original, unopened condition. Damaged-in-transit claims must be reported within 48 hours of delivery with photos. Please see our Refund Policy for full details.",
    sortOrder: 3,
    active: true,
  },
  {
    id: "faq-004",
    question: "How do I place a pre-order?",
    answer: "Pre-orders can be placed directly on the product page. Pre-order items require full payment upfront. You will be notified via WhatsApp and email as soon as your item ships.",
    sortOrder: 4,
    active: true,
  },
  {
    id: "faq-005",
    question: "What are Hobson Coins?",
    answer: "Hobson Coins is our loyalty rewards programme. You earn 1 coin for every ₹100 spent. Coins can be redeemed on future orders (up to 20% of the cart value, minimum 100 coins).",
    sortOrder: 5,
    active: true,
  },
  {
    id: "faq-006",
    question: "Can I cancel or modify an order?",
    answer: "Orders can be cancelled before they are shipped. To cancel or modify, contact us immediately via WhatsApp or email. Once shipped, orders cannot be modified.",
    sortOrder: 6,
    active: true,
  },
  {
    id: "faq-007",
    question: "Do you accept EMI payments?",
    answer: "Yes! We offer No Cost EMI on orders above ₹6,000 through major credit cards. Standard EMI options are available for all credit cards via our payment gateway.",
    sortOrder: 7,
    active: true,
  },
  {
    id: "faq-008",
    question: "Can I visit your physical store?",
    answer: "Absolutely! We have two stores — in Pune (Koregaon Park Annexe) and Bengaluru (Indiranagar). Store hours are Monday to Saturday, 10 AM to 7 PM IST.",
    sortOrder: 8,
    active: true,
  },
];

// ─── Discounts ────────────────────────────────────────────────────────────────

export const SEED_DISCOUNTS = [
  {
    id: "WELCOME10",    // Firestore doc ID = code
    code: "WELCOME10",
    type: "percent" as const,
    value: 10,
    minOrderValue: 999,
    maxUses: 500,
    usedCount: 0,
    active: true,
  },
  {
    id: "FLAT500",
    code: "FLAT500",
    type: "flat" as const,
    value: 500,
    minOrderValue: 3000,
    maxUses: 200,
    usedCount: 0,
    active: true,
  },
  {
    id: "HOBSON15",
    code: "HOBSON15",
    type: "percent" as const,
    value: 15,
    minOrderValue: 4999,
    maxUses: 100,
    usedCount: 0,
    active: true,
  },
  {
    id: "ANIME20",
    code: "ANIME20",
    type: "percent" as const,
    value: 20,
    minOrderValue: 2999,
    maxUses: 150,
    usedCount: 0,
    applicableCollections: ["anime"],
    active: true,
  },
];

// ─── Order Status Config ──────────────────────────────────────────────────────

export const SEED_ORDER_STATUS_CONFIG = [
  {
    id: "pending_payment",
    status: "pending_payment",
    label: "Pending Payment",
    color: "amber",
    notifyCustomer: false,
    waTemplate: "Hi {name}, your order #{orderId} is awaiting payment confirmation.",
    sortOrder: 1,
  },
  {
    id: "payment_confirmed",
    status: "payment_confirmed",
    label: "Payment Confirmed",
    color: "blue",
    notifyCustomer: true,
    waTemplate: "Hi {name}! Payment for order #{orderId} has been confirmed. We're processing your order now. 🎉",
    sortOrder: 2,
  },
  {
    id: "processing",
    status: "processing",
    label: "Processing",
    color: "blue",
    notifyCustomer: false,
    waTemplate: "Hi {name}, order #{orderId} is being prepared for dispatch.",
    sortOrder: 3,
  },
  {
    id: "shipped",
    status: "shipped",
    label: "Shipped",
    color: "purple",
    notifyCustomer: true,
    waTemplate: "Hi {name}! Your order #{orderId} has been shipped via {courier}. Track it here: {trackingUrl}",
    sortOrder: 4,
  },
  {
    id: "out_for_delivery",
    status: "out_for_delivery",
    label: "Out for Delivery",
    color: "orange",
    notifyCustomer: true,
    waTemplate: "Hi {name}! Your order #{orderId} is out for delivery today. Please keep your phone handy 📦",
    sortOrder: 5,
  },
  {
    id: "delivered",
    status: "delivered",
    label: "Delivered",
    color: "green",
    notifyCustomer: true,
    waTemplate: "Hi {name}! Order #{orderId} has been delivered. We hope you love your new collectible! ⭐ Share a photo and tag us!",
    sortOrder: 6,
  },
  {
    id: "cancelled",
    status: "cancelled",
    label: "Cancelled",
    color: "red",
    notifyCustomer: true,
    waTemplate: "Hi {name}, order #{orderId} has been cancelled. Refund (if any) will be processed within 5–7 business days.",
    sortOrder: 7,
  },
  {
    id: "refund_initiated",
    status: "refund_initiated",
    label: "Refund Initiated",
    color: "gray",
    notifyCustomer: true,
    waTemplate: "Hi {name}, refund for order #{orderId} has been initiated. Please allow 5–7 business days.",
    sortOrder: 8,
  },
];

// ─── Content Pages ────────────────────────────────────────────────────────────

export const SEED_PAGES = [
  {
    id: "about",
    slug: "about",
    title: "About Hobson Collectibles",
    body: `<h2>India's Premier Collectibles Store</h2>
<p>Hobson Collectibles was founded by passionate collectors for passionate collectors. With physical stores in Pune and Bengaluru, and nationwide shipping, we bring the world's finest licensed collectibles to Indian fans at fair prices.</p>
<h3>Our Promise</h3>
<ul>
  <li><strong>100% Authentic</strong> — Authorised dealer for all major brands</li>
  <li><strong>Secure Packaging</strong> — Every piece is triple-protected for transit</li>
  <li><strong>Expert Advice</strong> — Our team are collectors themselves</li>
  <li><strong>Loyalty Rewards</strong> — Earn Hobson Coins on every purchase</li>
</ul>
<h3>Brands We Carry</h3>
<p>Hot Toys, Sideshow Collectibles, Iron Studios, McFarlane Toys, Bandai, ThreeZero, Prime 1 Studio, XM Studios, and many more.</p>`,
    seoTitle: "About Us — Hobson Collectibles",
    seoDescription: "Learn about Hobson Collectibles — India's authorised dealer for premium action figures and statues.",
  },
  {
    id: "contact",
    slug: "contact",
    title: "Contact Us",
    body: `<h2>Get in Touch</h2>
<p>We'd love to hear from you! Reach us via any of the channels below.</p>
<h3>WhatsApp (Fastest Response)</h3>
<p>Send us a message on WhatsApp and we'll reply within hours: <a href="https://wa.me/919999999999">+91 99999 99999</a></p>
<h3>Email</h3>
<p><a href="mailto:support@hobsoncollectibles.in">support@hobsoncollectibles.in</a></p>
<h3>Store Locations</h3>
<p><strong>Pune:</strong> Shop 12, Koregaon Park Annexe, Pune 411001 — Mon–Sat 10 AM to 7 PM</p>
<p><strong>Bengaluru:</strong> Unit 4, Indiranagar 100 Ft Road, Bengaluru 560038 — Mon–Sat 10 AM to 7 PM</p>`,
    seoTitle: "Contact Us — Hobson Collectibles",
    seoDescription: "Contact Hobson Collectibles via WhatsApp, email, or visit our stores in Pune and Bengaluru.",
  },
];

// ─── Blog Posts ───────────────────────────────────────────────────────────────

export const SEED_BLOG_POSTS = [
  {
    id: "blog-hot-toys-2026",
    title: "Hot Toys 2026 Line-Up: Everything You Need to Know",
    slug: "hot-toys-2026-lineup",
    coverImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=1200&q=80",
    excerpt: "Hot Toys has unveiled their 2026 catalogue and it's packed with MCU, DC, and Star Wars gems.",
    body: `<h2>Hot Toys 2026: A Year of Epic Collectibles</h2>
<p>2026 is shaping up to be one of Hot Toys' most ambitious years yet. From the new Avengers wave to their expanded Star Wars line, there's something for every collector.</p>
<h3>Marvel Highlights</h3>
<p>The Iron Man Mark L gets an anniversary re-release with updated deco, and a new Spider-Man Symbiote variant has been confirmed for Q2. The Avengers Campus figures are particularly exciting for Disney Parks fans.</p>
<h3>DC Expansions</h3>
<p>Following the success of Batman Arkham Knight, Hot Toys is doubling down on the DC gaming line with a Gotham Knights Nightwing and a highly anticipated Deathstroke.</p>
<h3>Where to Pre-Order</h3>
<p>All 2026 Hot Toys figures are available for pre-order at Hobson Collectibles. Use code HOTNEW2026 for 5% off your first pre-order.</p>`,
    tags: ["hot-toys", "marvel", "dc", "star-wars", "2026"],
    authorName: "Hobson Team",
    published: true,
  },
  {
    id: "blog-beginners-guide",
    title: "Beginner's Guide to Collecting Action Figures in India",
    slug: "beginners-guide-collecting-action-figures-india",
    coverImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200&q=80",
    excerpt: "New to the hobby? We walk you through budgeting, brands, and what to look for when buying your first collectible.",
    body: `<h2>Welcome to the World of Collectibles</h2>
<p>Getting started with premium collectibles can feel overwhelming. Here's everything you need to know to buy smart from day one.</p>
<h3>Setting a Budget</h3>
<p>Entry-level collectibles start around ₹1,999 (McFarlane 7-inch figures). Mid-tier pieces from Iron Studios or Bandai S.H.Figuarts range from ₹4,000–₹12,000. High-end Hot Toys and Sideshow figures run ₹20,000–₹80,000+.</p>
<h3>Choosing Your First Piece</h3>
<p>Start with a character you absolutely love. A collectible you're emotionally invested in will always be worth it, regardless of resale value.</p>
<h3>Authenticity Check</h3>
<p>Always buy from an authorised dealer like Hobson Collectibles. Check for: official brand stickers, original inner box, numbered certificates, and country-of-origin labels.</p>
<h3>Storage & Display</h3>
<p>Keep figures away from direct sunlight to prevent discolouration. Use UV-filtering display cases for premium pieces.</p>`,
    tags: ["guide", "beginner", "tips", "collecting"],
    authorName: "Hobson Team",
    published: true,
  },
  {
    id: "blog-anime-figures-2026",
    title: "Top 10 Anime Figures to Buy in 2026",
    slug: "top-10-anime-figures-2026",
    coverImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=1200&q=80",
    excerpt: "From Demon Slayer to One Piece Gear 5 — the anime figures every collector should own in 2026.",
    body: `<h2>The Best Anime Collectibles of 2026</h2>
<p>Anime collectibles have never been hotter. Here are the must-have pieces for this year.</p>
<h3>1. Luffy Gear 5 — Bandai S.H.Figuarts</h3>
<p>Sun God Nika form is finally here in S.H.Figuarts quality. Incredible laugh-effect parts and articulation that lets you recreate every iconic moment.</p>
<h3>2. Tanjiro Kamado Water Breathing — Bandai S.H.Figuarts</h3>
<p>The detail on the water breathing effects is stunning. This is easily the best Tanjiro figure on the market.</p>
<h3>3. Naruto Rikudō Sennin Mode — Bandai S.H.Figuarts</h3>
<p>Available on pre-order now, this Naruto figure in Six Paths Sage Mode is set to be the definitive Naruto collectible.</p>
<p>Check out our full <a href="/collections/anime">Anime collection</a> for all available and pre-order items.</p>`,
    tags: ["anime", "dragon-ball-z", "demon-slayer", "one-piece", "naruto", "2026"],
    authorName: "Hobson Team",
    published: true,
  },
];

// ─── Franchises ───────────────────────────────────────────────────────────────

export const SEED_FRANCHISES = [
  {
    slug: "marvel",
    name: "Marvel",
    bannerImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&q=80",
    description: "Iconic Marvel super-heroes from Iron Man to Spider-Man.",
    seoTitle: "Marvel Collectibles — Hobson Collectibles",
    seoDescription: "Shop premium Marvel action figures and statues.",
    active: true,
    sortOrder: 1,
  },
  {
    slug: "dc",
    name: "DC Comics",
    bannerImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&q=80",
    description: "Collectibles from the DC universe — Batman, Superman, Wonder Woman & more.",
    active: true,
    sortOrder: 2,
  },
  {
    slug: "star-wars",
    name: "Star Wars",
    bannerImage: "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    description: "A galaxy far, far away — brought to life in stunning detail.",
    active: true,
    sortOrder: 3,
  },
  {
    slug: "anime",
    name: "Anime",
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    description: "Dragon Ball Z, Demon Slayer, One Piece, Attack on Titan & more.",
    active: true,
    sortOrder: 4,
  },
  {
    slug: "game-of-thrones",
    name: "Game of Thrones",
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    description: "Seven Kingdoms collectibles — dragons, knights, and Iron Throne.",
    active: true,
    sortOrder: 5,
  },
  {
    slug: "warhammer",
    name: "Warhammer",
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    description: "Warhammer 40K and Age of Sigmar premium figures.",
    active: true,
    sortOrder: 6,
  },
  {
    slug: "tmnt",
    name: "TMNT",
    bannerImage: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=800&q=80",
    description: "Teenage Mutant Ninja Turtles — Leonardo, Donatello, Michelangelo & Raphael.",
    active: true,
    sortOrder: 7,
  },
  {
    slug: "transformers",
    name: "Transformers",
    bannerImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
    description: "Autobots vs. Decepticons — from G1 classics to blockbuster film editions.",
    active: true,
    sortOrder: 8,
  },
  {
    slug: "gi-joe",
    name: "G.I. Joe",
    bannerImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "America's elite fighting force — G.I. Joe Classified Series and vintage homages.",
    active: true,
    sortOrder: 9,
  },
  {
    slug: "masters-of-the-universe",
    name: "Masters of the Universe",
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    description: "He-Man, Skeletor and the legendary heroes of Eternia.",
    active: true,
    sortOrder: 10,
  },
  {
    slug: "jujutsu-kaisen",
    name: "Jujutsu Kaisen",
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    description: "Gojo, Itadori & Megumi — premium Jujutsu Kaisen collectibles.",
    active: true,
    sortOrder: 11,
  },
  {
    slug: "harry-potter",
    name: "Harry Potter",
    bannerImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    description: "Wizarding World collectibles — from Hogwarts to the Ministry of Magic.",
    active: true,
    sortOrder: 12,
  },
  {
    slug: "terminator",
    name: "Terminator",
    bannerImage: "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    description: "I'll be back — iconic Terminator figures from Hot Toys and NECA.",
    active: true,
    sortOrder: 13,
  },
  {
    slug: "horror",
    name: "Horror",
    bannerImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    description: "Freddy Krueger, Michael Myers, Jason Voorhees & more — premium horror collectibles.",
    active: true,
    sortOrder: 14,
  },
  {
    slug: "sci-fi",
    name: "Sci-Fi",
    bannerImage: "https://images.unsplash.com/photo-1563656157432-67560011e209?w=800&q=80",
    description: "The Matrix, Alien, Predator, RoboCop and other iconic sci-fi universe collectibles.",
    active: true,
    sortOrder: 15,
  },
  {
    slug: "image-comics",
    name: "Image Comics",
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    description: "Spawn, Invincible, The Walking Dead and other Image Comics universe collectibles.",
    active: true,
    sortOrder: 16,
  },
];

// ─── Brands ───────────────────────────────────────────────────────────────────

export const SEED_BRANDS = [
  {
    slug: "hot-toys",
    name: "Hot Toys",
    bannerImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1608889175638-9322300c46e8?w=200&q=80",
    description: "Sixth-scale masterpieces with hyper-realistic likenesses.",
    active: true,
    sortOrder: 1,
  },
  {
    slug: "sideshow",
    name: "Sideshow Collectibles",
    bannerImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&q=80",
    description: "World-class premium collectible statues and figures.",
    active: true,
    sortOrder: 2,
  },
  {
    slug: "iron-studios",
    name: "Iron Studios",
    bannerImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=200&q=80",
    description: "Brazilian craftsmen behind iconic 1:10 Battle Dioramas.",
    active: true,
    sortOrder: 3,
  },
  {
    slug: "mcfarlane",
    name: "McFarlane Toys",
    bannerImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&q=80",
    description: "Highly detailed collector-grade action figures at accessible prices.",
    active: true,
    sortOrder: 4,
  },
  {
    slug: "bandai",
    name: "Bandai",
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=200&q=80",
    description: "S.H.Figuarts, Metal Build, and other premium Bandai lines.",
    active: true,
    sortOrder: 5,
  },
  {
    slug: "threezero",
    name: "ThreeZero",
    bannerImage: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=200&q=80",
    description: "Iconic 1/6 and 1/12 scale collectibles with exceptional detail.",
    active: true,
    sortOrder: 6,
  },
  {
    slug: "neca",
    name: "NECA",
    bannerImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&q=80",
    description: "Ultimate action figures for movie, TV, and gaming icons — from Freddy Krueger to TMNT.",
    active: true,
    sortOrder: 7,
  },
  {
    slug: "mezco",
    name: "Mezco Toyz",
    bannerImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&q=80",
    description: "One:12 Collective — premium soft-goods action figures with unparalleled detail.",
    active: true,
    sortOrder: 8,
  },
  {
    slug: "prime-1-studio",
    name: "Prime 1 Studio",
    bannerImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&q=80",
    description: "Ultra-premium museum-quality polystone statues and life-size replicas.",
    active: true,
    sortOrder: 9,
  },
  {
    slug: "inart",
    name: "InArt",
    bannerImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=200&q=80",
    description: "Hyper-real 1/6 and 1/12 scale collectible figures with silicone skin technology.",
    active: true,
    sortOrder: 10,
  },
  {
    slug: "funko",
    name: "Funko",
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=200&q=80",
    description: "Pop! vinyl figures and collectibles for every fandom — affordable and fun.",
    active: true,
    sortOrder: 11,
  },
  {
    slug: "hasbro",
    name: "Hasbro",
    bannerImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&q=80",
    description: "Marvel Legends, G.I. Joe Classified, Star Wars Black Series — collector-grade 6-inch figures.",
    active: true,
    sortOrder: 12,
  },
  {
    slug: "kaiyodo",
    name: "Kaiyodo / Revoltech",
    bannerImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=200&q=80",
    description: "Revolutionary joint system — Revoltech Amazing Yamaguchi and figurative anime figures.",
    active: true,
    sortOrder: 13,
  },
  {
    slug: "mattel",
    name: "Mattel",
    bannerImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=800&q=80",
    logoImage: "https://images.unsplash.com/photo-1526400473556-aac12354f3db?w=200&q=80",
    description: "Masters of the Universe Masterverse, Hot Wheels, and other Mattel collector lines.",
    active: true,
    sortOrder: 14,
  },
];

// ─── Curated Collections ──────────────────────────────────────────────────────

export const SEED_CURATED_COLLECTIONS = [
  {
    slug: "whats-new",
    name: "What's New",
    description: "The latest arrivals and freshest releases at Hobson.",
    active: true,
    sortOrder: 1,
  },
  {
    slug: "16-scale",
    name: "1/6 Scale",
    description: "Premium sixth-scale figures from Hot Toys, ThreeZero, and more.",
    active: true,
    sortOrder: 2,
  },
  {
    slug: "110-scale",
    name: "1/10 Scale",
    description: "BDS Art Scale and Battle Diorama figures from Iron Studios.",
    active: true,
    sortOrder: 3,
  },
  {
    slug: "preorder",
    name: "Pre-order",
    description: "Secure yours before it sells out — ships on release.",
    active: true,
    sortOrder: 4,
  },
  {
    slug: "statues",
    name: "Statues & Dioramas",
    description: "Premium polystone and resin statues from Sideshow and Iron Studios.",
    active: true,
    sortOrder: 5,
  },
  {
    slug: "under-5000",
    name: "Under ₹5,000",
    description: "High-quality collectibles at approachable price points.",
    active: true,
    sortOrder: 6,
  },
  {
    slug: "transformers-collection",
    name: "Transformers",
    description: "Autobots and Decepticons — MDLX, DLX, and G1 classics.",
    filterFranchises: ["transformers"],
    active: true,
    sortOrder: 7,
  },
  {
    slug: "gi-joe-collection",
    name: "G.I. Joe Classified",
    description: "Hasbro's elite G.I. Joe Classified Series 6-inch figures.",
    filterFranchises: ["gi-joe"],
    active: true,
    sortOrder: 8,
  },
  {
    slug: "marvel-legends-collection",
    name: "Marvel Legends",
    description: "Hasbro Marvel Legends 6-inch figures for every Marvel character.",
    filterFranchises: ["marvel"],
    filterBrands: ["hasbro"],
    active: true,
    sortOrder: 9,
  },
  {
    slug: "anime-collection",
    name: "Anime",
    description: "Dragon Ball Z, Demon Slayer, One Piece, Attack on Titan, JJK & more.",
    filterFranchises: ["anime", "jujutsu-kaisen"],
    active: true,
    sortOrder: 10,
  },
];

// ─── Payment Settings (singleton) ────────────────────────────────────────────

export const SEED_PAYMENT_SETTINGS = {
  _docId: "main",
  razorpayEnabled: false,
  razorpayKeyId: "",
  razorpayKeySecret: "",
  codEnabled: true,
  codFee: 0,
  codMaxOrderValue: 10000,
  whatsappEnabled: true,
  whatsappNumber: "919999999999",
  upiId: "",
  bankName: "",
  bankAccountNumber: "",
  bankIfsc: "",
  bankAccountHolder: "",
  paymentNote: "We accept UPI, cards, net banking, and COD.",
};

// ─── Shipping Settings (singleton) ────────────────────────────────────────────

export const SEED_SHIPPING_SETTINGS = {
  _docId: "main",
  freeShippingThreshold: 2999,
  standardShippingFee: 99,
  expressShippingFee: 299,
  gstPercent: 18,
  codFee: 0,
  shippingNote: "Free pan-India shipping on all orders above ₹2,999.",
  estimatedDeliveryDays: "3–7",
  expressDeliveryDays: "1–2",
  nonServiceablePincodes: [] as string[],
};

// ─── Navigation Config (singleton) ────────────────────────────────────────────

export const SEED_NAVIGATION_CONFIG = {
  _docId: "main",
  featuredFranchises: ["marvel", "dc", "star-wars", "anime"],
  featuredBrands: ["hot-toys", "sideshow", "iron-studios", "mcfarlane"],
  maxMegaMenuItems: 8,
  showBrandsInNav: true,
  showFranchisesInNav: true,
  showBlogInNav: true,
};

// ─── Character Hotspot (singleton) ───────────────────────────────────────────

export const SEED_CHARACTER_HOTSPOT = {
  _docId: "main",
  imageUrl: "/animevssuperhero.jpg",
  imageAlt: "DC, Marvel and Anime characters",
  active: true,
  pins: [
    {
      id: "spiderman",
      name: "SPIDER-MAN",
      universe: "Marvel",
      description:
        "Mid-swing, wall-crawling, Symbiote — Peter Parker in every iconic pose. Hot Toys & Iron Studios pieces with real fabric suits and LED arc detail. Ships India-wide.",
      href: "/en/franchise/marvel",
      xPct: 5,
      yPct: 22,
      accent: "#E8001C",
      badge: "MARVEL",
      buyText: "Get Spider-Man Figures",
    },
    {
      id: "ironman",
      name: "IRON MAN",
      universe: "Marvel",
      description:
        "Tony Stark's armour at display scale. Arc-reactor glow, battle-damaged panels, nano-tech variants — the cornerstone of every serious Marvel shelf.",
      href: "/en/franchise/marvel",
      xPct: 8,
      yPct: 58,
      accent: "#E8001C",
      badge: "MARVEL",
      buyText: "Get Iron Man Figures",
    },
    {
      id: "robin",
      name: "ROBIN",
      universe: "DC Comics",
      description:
        "Dick Grayson's acrobatic grace in resin. Flying-kick, staff-spin & Nightwing-transition statues — the most underrated must-have in the Bat-family lineup.",
      href: "/en/franchise/dc-comics",
      xPct: 22,
      yPct: 18,
      accent: "#4A90D9",
      badge: "DC",
      buyText: "Get Robin Figures",
    },
    {
      id: "batman",
      name: "BATMAN",
      universe: "DC Comics",
      description:
        "Gotham's Dark Knight on your shelf. Full-armoured, Nanosuit & Bat-suit variants from Hot Toys & Prime 1 Studio — every grim detail preserved in 1/6 scale.",
      href: "/en/franchise/dc-comics",
      xPct: 30,
      yPct: 42,
      accent: "#4A90D9",
      badge: "DC",
      buyText: "Get Batman Figures",
    },
    {
      id: "captain-america",
      name: "CAPTAIN AMERICA",
      universe: "Marvel",
      description:
        "Shield raised, Endgame-ready. WW2 Origin, MCU & Broken Shield variants — the most recognisable Marvel statue in any collection. Limited stock.",
      href: "/en/franchise/marvel",
      xPct: 24,
      yPct: 76,
      accent: "#0057FF",
      badge: "MARVEL",
      buyText: "Get Cap Figures",
    },
    {
      id: "superman",
      name: "SUPERMAN",
      universe: "DC Comics",
      description:
        "Kal-El soaring above your display. XM Studios & Iron Studios full-sculpt statues — classic red cape and New 52 dark variants, ready to ship.",
      href: "/en/franchise/dc-comics",
      xPct: 42,
      yPct: 68,
      accent: "#0057FF",
      badge: "DC",
      buyText: "Get Superman Figures",
    },
    {
      id: "goku",
      name: "SON GOKU",
      universe: "Dragon Ball",
      description:
        "Ultra Instinct, SSJ4, Kamehameha — every legendary form. S.H.Figuarts & Banpresto pieces sell out within hours of restock. Order yours today.",
      href: "/en/franchise/dragon-ball",
      xPct: 51,
      yPct: 36,
      accent: "#FFE500",
      badge: "ANIME",
      buyText: "Get Goku Figures",
    },
    {
      id: "naruto",
      name: "NARUTO UZUMAKI",
      universe: "Naruto Shippuden",
      description:
        "Sage Mode, Baryon Mode, Nine-Tails Chakra — Naruto's greatest forms frozen in resin. These restock and sell out within days. Don't sleep on it.",
      href: "/en/franchise/naruto",
      xPct: 57,
      yPct: 78,
      accent: "#FF6B00",
      badge: "ANIME",
      buyText: "Get Naruto Figures",
    },
    {
      id: "ichigo",
      name: "ICHIGO KUROSAKI",
      universe: "Bleach",
      description:
        "Bankai Tensa Zangetsu, Hollow & Final Getsuga forms — some of anime's most dramatic poses. Bleach figures are rare. When they restock, they go fast.",
      href: "/en/franchise/bleach",
      xPct: 70,
      yPct: 20,
      accent: "#4A90D9",
      badge: "ANIME",
      buyText: "Get Ichigo Figures",
    },
    {
      id: "luffy",
      name: "MONKEY D. LUFFY",
      universe: "One Piece",
      description:
        "Gear 5, Red Roc, Boundman — Luffy's explosive power takes centre stage. One Piece is the fastest-moving anime series on our platform. Grab yours now.",
      href: "/en/franchise/one-piece",
      xPct: 80,
      yPct: 50,
      accent: "#FFE500",
      badge: "ANIME",
      buyText: "Get Luffy Figures",
    },
    {
      id: "saitama",
      name: "SAITAMA",
      universe: "One Punch Man",
      description:
        "One punch. That's all it takes. From deadpan standing pose to the single devastating strike — Saitama figures are deceptively brilliant shelf pieces.",
      href: "/en/franchise/one-punch-man",
      xPct: 91,
      yPct: 50,
      accent: "#FFE500",
      badge: "ANIME",
      buyText: "Get Saitama Figures",
    },
  ],
};

// ─── All seed entity IDs (for the admin seeding page) ────────────────────────

export const SEED_ENTITY_MAP = {
  products: SEED_PRODUCTS.map((p) => p.id),
  collections: SEED_COLLECTIONS.map((c) => c.slug),
  franchises: SEED_FRANCHISES.map((f) => f.slug),
  brands: SEED_BRANDS.map((b) => b.slug),
  curatedCollections: SEED_CURATED_COLLECTIONS.map((c) => c.slug),
  banners: SEED_BANNERS.map((b) => b.id),
  promobanners: SEED_PROMO_BANNERS.map((b) => b.id),
  trustBadges: SEED_TRUST_BADGES.map((b) => b.id),
  homeSections: SEED_HOME_SECTIONS.map((s) => s.id),
  announcements: SEED_ANNOUNCEMENTS.map((a) => a.id),
  testimonials: SEED_TESTIMONIALS.map((t) => t.id),
  faq: SEED_FAQ.map((f) => f.id),
  discounts: SEED_DISCOUNTS.map((d) => d.id),
  orderStatusConfig: SEED_ORDER_STATUS_CONFIG.map((s) => s.id),
  pages: SEED_PAGES.map((p) => p.id),
  blogPosts: SEED_BLOG_POSTS.map((b) => b.id),
  // singletons — seeded by docId
  siteConfig: ["main"],
  loyaltyConfig: ["main"],
  paymentSettings: ["main"],
  shippingSettings: ["main"],
  navigationConfig: ["main"],
  characterHotspot: ["main"],
};

// ─── Seed Admin User ─────────────────────────────────────────────────────────

/** Fixed credentials for the dev/seed admin account */
export const SEED_ADMIN_USER = {
  uid: "seed-admin-001",
  email: "admin@hobsoncollectibles.com",
  get password() {
    const pwd = process.env.SEED_ADMIN_PASSWORD;
    if (!pwd) throw new Error("SEED_ADMIN_PASSWORD env var must be set before running the seed script.");
    return pwd;
  },
  displayName: "Hobson Admin",
  role: "admin" as const,
};

/** Summary counts for quick reference */
export const SEED_SUMMARY = {
  products: SEED_PRODUCTS.length,
  franchises: SEED_FRANCHISES.length,
  brands: SEED_BRANDS.length,
  curatedCollections: SEED_CURATED_COLLECTIONS.length,
  testimonials: SEED_TESTIMONIALS.length,
  faqItems: SEED_FAQ.length,
  discounts: SEED_DISCOUNTS.length,
  banners: SEED_BANNERS.length,
  promobanners: SEED_PROMO_BANNERS.length,
  trustBadges: SEED_TRUST_BADGES.length,
  blogPosts: SEED_BLOG_POSTS.length,
  pages: SEED_PAGES.length,
};
